// Multi-template system - stores theme presets for sale
import type { ThemeConfig } from './types';

export interface TemplatePreset {
  id: string;
  name: string;
  description: string;
  thumbnail: string;
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    bg: string;
    text: string;
    gold: string;
    terracotta: string;
  };
  fontHeading: string;
  fontBody: string;
  cardRadius: number;
  ornamentStyle: 'leaves' | 'floral' | 'geometric' | 'minimal';
  ornamentDensity: 'low' | 'medium' | 'high';
  animationIntensity: 'subtle' | 'medium' | 'vibrant';
  isPremium: boolean;
}

export const templatePresets: TemplatePreset[] = [
  {
    id: 'modern-organic-luxury',
    name: 'Modern Organic Luxury',
    description: 'Elegan alami dengan sentuhan emas, sage, dan forest green. Cocok untuk outdoor & garden wedding.',
    thumbnail: '🎋',
    colors: { primary: '#22382D', secondary: '#6F7F55', accent: '#A9B89B', bg: '#F7F1E6', text: '#22382D', gold: '#C9A86A', terracotta: '#B86B4B' },
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    cardRadius: 24,
    ornamentStyle: 'leaves',
    ornamentDensity: 'medium',
    animationIntensity: 'medium',
    isPremium: false,
  },
  {
    id: 'classic-rose-gold',
    name: 'Classic Rose Gold',
    description: 'Romantis dan anggun dengan palet dusty pink, rose gold, dan cream. Cocok untuk ballroom.',
    thumbnail: '🌹',
    colors: { primary: '#8B5E63', secondary: '#D4A9A7', accent: '#E8D5C4', bg: '#FEFAF6', text: '#4A3B3C', gold: '#D4A9A7', terracotta: '#C4918C' },
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    cardRadius: 20,
    ornamentStyle: 'floral',
    ornamentDensity: 'high',
    animationIntensity: 'vibrant',
    isPremium: true,
  },
  {
    id: 'minimal-monochrome',
    name: 'Minimal Monochrome',
    description: 'Simpel modern dengan palet monokrom hangat. Cocok untuk intimate & modern wedding.',
    thumbnail: '⬜',
    colors: { primary: '#2D2D2D', secondary: '#6B6B6B', accent: '#A0A0A0', bg: '#FAFAFA', text: '#1A1A1A', gold: '#D4AF37', terracotta: '#C0A080' },
    fontHeading: 'Cormorant Garamond',
    fontBody: 'Inter',
    cardRadius: 12,
    ornamentStyle: 'minimal',
    ornamentDensity: 'low',
    animationIntensity: 'subtle',
    isPremium: true,
  },
  {
    id: 'tropical-paradise',
    name: 'Tropical Paradise',
    description: 'Ceria dan segar dengan palet hijau tropis, coral, dan putih. Cocok untuk beach & destination wedding.',
    thumbnail: '🌴',
    colors: { primary: '#1B4332', secondary: '#40916C', accent: '#52B788', bg: '#F0F7F4', text: '#1B4332', gold: '#D4A373', terracotta: '#E76F51' },
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    cardRadius: 28,
    ornamentStyle: 'leaves',
    ornamentDensity: 'high',
    animationIntensity: 'vibrant',
    isPremium: true,
  },
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    description: 'Mewah dan dramatis dengan ungu, gold, dan hitam. Cocok untuk evening & formal wedding.',
    thumbnail: '💜',
    colors: { primary: '#2D1B4E', secondary: '#6B3FA0', accent: '#9B7FC1', bg: '#F8F5FC', text: '#1A1030', gold: '#D4AF37', terracotta: '#C4A882' },
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    cardRadius: 16,
    ornamentStyle: 'geometric',
    ornamentDensity: 'medium',
    animationIntensity: 'medium',
    isPremium: true,
  },
  {
    id: 'sakura-pink',
    name: 'Sakura Pink',
    description: 'Lembut dan romantis dengan palet pink Jepang, putih, dan dusty rose. Cocok untuk spring & garden wedding.',
    thumbnail: '🌸',
    colors: { primary: '#D4A0A7', secondary: '#E8C5CA', accent: '#F0D5D8', bg: '#FFF5F7', text: '#4A3040', gold: '#D4AF37', terracotta: '#C4918C' },
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    cardRadius: 24,
    ornamentStyle: 'floral',
    ornamentDensity: 'high',
    animationIntensity: 'vibrant',
    isPremium: true,
  },
  {
    id: 'vintage-kraft',
    name: 'Vintage Kraft',
    description: 'Klasik nostalgia dengan palet kraft, coklat, dan cream. Cocok untuk rustic & vintage wedding.',
    thumbnail: '📜',
    colors: { primary: '#6B4226', secondary: '#8B5E3C', accent: '#D4A373', bg: '#FEFAE0', text: '#3C2415', gold: '#D4A373', terracotta: '#BC6C25' },
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    cardRadius: 12,
    ornamentStyle: 'floral',
    ornamentDensity: 'medium',
    animationIntensity: 'subtle',
    isPremium: true,
  },
  {
    id: 'aureum-gold',
    name: 'Aureum Gold',
    description: 'Ultra-mewah dengan palet ivory, champagne gold, dan putih. Kemewahan murni untuk luxury & ballroom wedding.',
    thumbnail: '👑',
    colors: { primary: '#2D2A24', secondary: '#C9A86A', accent: '#E8D5A3', bg: '#FAF8F2', text: '#2D2A24', gold: '#C9A86A', terracotta: '#C4A882' },
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    cardRadius: 8,
    ornamentStyle: 'minimal',
    ornamentDensity: 'low',
    animationIntensity: 'medium',
    isPremium: true,
  },
  {
    id: 'celestial-night',
    name: 'Celestial Night',
    description: 'Magis elegan dengan palet midnight navy, silver, dan starlight. Cocok untuk evening & starry night wedding.',
    thumbnail: '🌙',
    colors: { primary: '#0B1930', secondary: '#132744', accent: '#C8D6E5', bg: '#0B1930', text: '#E8EDF2', gold: '#D4AF37', terracotta: '#C4A882' },
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    cardRadius: 16,
    ornamentStyle: 'geometric',
    ornamentDensity: 'medium',
    animationIntensity: 'vibrant',
    isPremium: true,
  },
  {
    id: 'terracotta-bloom',
    name: 'Terracotta Bloom',
    description: 'Boho rustic hangat dengan palet terracotta, sage, dan cream. Cocok untuk outdoor & garden wedding.',
    thumbnail: '🏵️',
    colors: { primary: '#C7734B', secondary: '#8B9D7D', accent: '#D4956B', bg: '#FBF7F0', text: '#5D4037', gold: '#D4A373', terracotta: '#C7734B' },
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    cardRadius: 20,
    ornamentStyle: 'leaves',
    ornamentDensity: 'medium',
    animationIntensity: 'medium',
    isPremium: true,
  },
  {
    id: 'ocean-breeze',
    name: 'Ocean Breeze',
    description: 'Segar coastal dengan palet navy, aquamarine, dan putih. Cocok untuk beach & destination wedding.',
    thumbnail: '🌊',
    colors: { primary: '#1B2A4A', secondary: '#5DBCD2', accent: '#8FD8E8', bg: '#FCFCFC', text: '#1B2A4A', gold: '#D4AF37', terracotta: '#C7734B' },
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    cardRadius: 12,
    ornamentStyle: 'minimal',
    ornamentDensity: 'low',
    animationIntensity: 'subtle',
    isPremium: true,
  },
  {
    id: 'jasmine-white',
    name: 'Jasmine Pure',
    description: 'Ultra-minimal elegan dengan palet all-white, silver, dan champagne. Cocok untuk modern intimate wedding.',
    thumbnail: '🤍',
    colors: { primary: '#1A1A1A', secondary: '#C0C4CC', accent: '#E8D5B5', bg: '#FFFFFF', text: '#1A1A1A', gold: '#E8D5B5', terracotta: '#C4A882' },
    fontHeading: 'Cormorant Garamond',
    fontBody: 'Inter',
    cardRadius: 4,
    ornamentStyle: 'minimal',
    ornamentDensity: 'low',
    animationIntensity: 'subtle',
    isPremium: true,
  },
  {
    id: 'dream-garden',
    name: 'Dream Garden',
    description: 'Dreamy pastel aesthetic dengan nuansa garden party. Soft, ethereal, magical — seperti berjalan di taman mimpi.',
    thumbnail: '🪷',
    colors: { primary: '#4A3B4A', secondary: '#E8B4C8', accent: '#C5B9E0', bg: '#FFF8F5', text: '#4A3B4A', gold: '#E8C5A0', terracotta: '#E8B4C8' },
    fontHeading: 'Playfair Display',
    fontBody: 'Poppins',
    cardRadius: 24,
    ornamentStyle: 'floral',
    ornamentDensity: 'high',
    animationIntensity: 'vibrant',
    isPremium: true,
  },
  {
    id: 'javanese-elegance',
    name: 'Javanese Elegance',
    description: 'Kemewahan tradisional Jawa dengan gold & burgundy. Terinspirasi dari kemegahan keraton — formal, anggun, berkelas.',
    thumbnail: '🏮',
    colors: { primary: '#4A0E2E', secondary: '#D4AF37', accent: '#C4A882', bg: '#FDF8F0', text: '#1A0A10', gold: '#D4AF37', terracotta: '#5C3A21' },
    fontHeading: 'Playfair Display',
    fontBody: 'Poppins',
    cardRadius: 8,
    ornamentStyle: 'geometric',
    ornamentDensity: 'medium',
    animationIntensity: 'subtle',
    isPremium: true,
  },
  {
    id: 'aire-royale',
    name: 'Aire Royale',
    description: 'Dark luxury dengan purple gradient & gold accents. Replika eksklusif our-wedding.link — boutique, elegan, dan dramatis.',
    thumbnail: '💎',
    colors: { primary: '#0A0A14', secondary: '#550979', accent: '#D4AF37', bg: '#0A0A14', text: '#F5F0EB', gold: '#D4AF37', terracotta: '#C4A882' },
    fontHeading: 'Playfair Display',
    fontBody: 'Cormorant Garamond',
    cardRadius: 2,
    ornamentStyle: 'geometric',
    ornamentDensity: 'low',
    animationIntensity: 'subtle',
    isPremium: true,
  },
  {
    id: 'sage-dream',
    name: 'Sage Dream',
    description: 'Soft botanical dream dengan sage green, ivory warmth, dan soft gold. Terinspirasi dari taman rahasia — premium, romantis, dan elegan.',
    thumbnail: '🌱',
    colors: { primary: '#4A6741', secondary: '#7A8B6E', accent: '#B8C5A8', bg: '#FBF9F4', text: '#2D2E24', gold: '#C9A86A', terracotta: '#B86B4B' },
    fontHeading: 'Playfair Display',
    fontBody: 'Poppins',
    cardRadius: 20,
    ornamentStyle: 'floral',
    ornamentDensity: 'medium',
    animationIntensity: 'medium',
    isPremium: true,
  },
  {
    id: 'premium-blush',
    name: 'Premium Blush',
    description: 'Romantic sweetness dengan palet dusty rose, cream, dan soft coral. Terinspirasi dari bunga mawar — manis, feminin, elegan.',
    thumbnail: '💗',
    colors: { primary: '#D4756B', secondary: '#E8B4B8', accent: '#F0D5D8', bg: '#FFF5F5', text: '#4A3035', gold: '#D4AF37', terracotta: '#C4918C' },
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    cardRadius: 24,
    ornamentStyle: 'floral',
    ornamentDensity: 'high',
    animationIntensity: 'vibrant',
    isPremium: true,
  },
  {
    id: 'luxury-lavender',
    name: 'Luxury Lavender',
    description: 'Elegansi ungu dengan palet lavender, cream, dan gold. Aura magis dan kemewahan yang menenangkan.',
    thumbnail: '🦋',
    colors: { primary: '#6B3FA0', secondary: '#9B7FC1', accent: '#C5B9E0', bg: '#F9F5FD', text: '#2D1B4E', gold: '#D4AF37', terracotta: '#C4A882' },
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    cardRadius: 20,
    ornamentStyle: 'floral',
    ornamentDensity: 'medium',
    animationIntensity: 'medium',
    isPremium: true,
  },
  {
    id: 'exclusive-noir',
    name: 'Exclusive Noir',
    description: 'Dark high-contrast luxury dengan palet black, white, dan rose gold. Misterius, eksklusif, unforgettable.',
    thumbnail: '🖤',
    colors: { primary: '#1A1A24', secondary: '#2D2D3A', accent: '#D4A9A7', bg: '#0F0F12', text: '#F0EDE8', gold: '#D4A9A7', terracotta: '#C4918C' },
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    cardRadius: 4,
    ornamentStyle: 'minimal',
    ornamentDensity: 'low',
    animationIntensity: 'subtle',
    isPremium: true,
  },
  {
    id: 'eternal-sage-luxury',
    name: 'Eternal Sage Luxury',
    description: 'Cinematic slow-zoom opening, botanical luxury dengan Forest Green, Ivory, dan Soft Gold. Pemenang penghargaan — template terbaik dengan 100dvh cover dan animasi sinematik.',
    thumbnail: '🌿',
    colors: { primary: '#1F2E26', secondary: '#6F7F55', accent: '#A9B89B', bg: '#F7F1E6', text: '#1F2E26', gold: '#C9A86A', terracotta: '#B86B4B' },
    fontHeading: 'Cormorant Garamond',
    fontBody: 'Inter',
    cardRadius: 24,
    ornamentStyle: 'floral',
    ornamentDensity: 'high',
    animationIntensity: 'medium',
    isPremium: false,
  },
  {
    id: 'wekita-elegance',
    name: 'Wekita Elegance',
    description: 'Inspired by premium Indonesian wedding invitations. Section card-based layout dengan vine decorations, monogram transisi, dan countdown live. Elegan, cinematic, mobile-first.',
    thumbnail: '🍃',
    colors: { primary: '#0d2518', secondary: '#8f9b73', accent: '#c6a461', bg: '#fbf6ea', text: '#2f2a22', gold: '#c6a461', terracotta: '#b86b4b' },
    fontHeading: 'Playfair Display',
    fontBody: 'Inter',
    cardRadius: 28,
    ornamentStyle: 'floral',
    ornamentDensity: 'high',
    animationIntensity: 'vibrant',
    isPremium: true,
  },
  {
    id: 'blush-romance',
    name: 'Blush Romance',
    description: 'Soft romantic dengan palet dusty rose, blush pink, dan rose gold. Cover light & airy dengan floating hearts, Great Vibes script font, dan swipe gallery carousel. Feminin, manis, dreamy.',
    thumbnail: '💕',
    colors: { primary: '#8B5E63', secondary: '#D4A9A7', accent: '#E8D5C4', bg: '#FFF5F5', text: '#4A2E30', gold: '#D4A9A7', terracotta: '#D4756B' },
    fontHeading: 'Great Vibes',
    fontBody: 'Montserrat',
    cardRadius: 24,
    ornamentStyle: 'floral',
    ornamentDensity: 'high',
    animationIntensity: 'vibrant',
    isPremium: true,
  },
];

export function getTemplateById(id: string): TemplatePreset | undefined {
  return templatePresets.find(t => t.id === id);
}

export function applyTemplateToTheme(template: TemplatePreset): ThemeConfig {
  return {
    primaryColor: template.colors.primary,
    secondaryColor: template.colors.secondary,
    accentColor: template.colors.accent,
    bgColor: template.colors.bg,
    textColor: template.colors.text,
    goldColor: template.colors.gold,
    fontHeading: template.fontHeading,
    fontBody: template.fontBody,
    cardRadius: template.cardRadius,
    ornamentDensity: template.ornamentDensity,
    animationIntensity: template.animationIntensity,
  };
}
